{
 "title": "Traces",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "serviceName",
    "label": "Service Name",
    "query": "SELECT DISTINCT ServiceName FROM otel_traces"
   },
   {
    "name": "trace_id",
    "label": "Trace Id",
    "query": "SELECT DISTINCT TraceId FROM otel_traces WHERE ParentSpanId = '' LIMIT 100"
   }
  ]
 },
 "panels": [
  {
   "title": "Services over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as time, ServiceName, count() as ` ` FROM otel_traces WHERE $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id) AND $__timeFilter(Timestamp)  AND ServiceName In (${serviceName:singlequote}) GROUP BY ServiceName, time ORDER BY time ASC LIMIT 100000"
    }
   ]
  },
  {
   "title": "Service Performance - p99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as time, ServiceName,\n\tquantile(0.99)(Duration)/1000000 AS p99 FROM otel_traces WHERE $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id) AND $__timeFilter(Timestamp) AND  ( Timestamp  >= $__fromTime AND Timestamp <= $__toTime ) AND ServiceName In (${serviceName:singlequote}) AND ServiceName != 'loadgenerator' GROUP BY time, ServiceName ORDER BY time ASC LIMIT 100000"
    }
   ]
  },
  {
   "title": "Error rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as time, count(*) as ` `,\n\tServiceName FROM otel_traces WHERE $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id) AND $__timeFilter(Timestamp) AND ServiceName In (${serviceName:singlequote}) AND StatusCode= 'STATUS_CODE_ERROR' and ServiceName != 'loadgenerator' GROUP BY ServiceName, time ORDER BY time ASC LIMIT 100000"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT min(Timestamp) as timestamp, TraceId as `Trace Id`, argMin(ServiceName, Timestamp) as `Service Name`, sum(Duration)/1000000 as Duration from otel_traces WHERE $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id)  AND ServiceName In (${serviceName:singlequote}) AND ServiceName != 'loadgenerator' AND $__timeFilter(Timestamp) GROUP BY TraceId ORDER BY Duration DESC LIMIT 100",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Trace Details",
   "type": "traces",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT TraceId as traceID, SpanId as spanID, SpanName as operationName, ParentSpanId as parentSpanID, ServiceName as serviceName, Duration/1000000 as duration, Timestamp as startTime, arrayMap(key -> map('key', key, 'value',SpanAttributes[key]), mapKeys(SpanAttributes)) as tags, arrayMap(key -> map('key', key, 'value',ResourceAttributes[key]), mapKeys(ResourceAttributes)) as serviceTags FROM otel_traces WHERE TraceId = '${trace_id}' ORDER BY startTime ASC",
     "selectedFormat": 3
    }
   ]
  },
  {
   "title": "Trace Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT Timestamp as timestamp, Body as body, SeverityText as level, TraceId as traceID, LogAttributes['service'] as ServiceName FROM \"default\".\"otel_logs\" WHERE TraceId = '${trace_id}' ORDER BY timestamp DESC LIMIT 1000",
     "selectedFormat": 4
    }
   ]
  }
 ]
}